### ISSUE TITLE
use internal ip not dns for meta data discovery

### ISSUE THREAD

**Issue by KenBarr** [SolaceProducts/solace-aws-ha-quickstart#40]
We use internal-data this does not always resolve to 169.254.169.254.
Might want to use static IP.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by KenBarr** [comment]
as per here:  using instance-data is an undocumented feature.
https://forums.aws.amazon.com/thread.jspa?threadID=149708

**Comment by bczoma** [comment]
PR https://github.com/SolaceProducts/solace-aws-ha-quickstart/pull/41 has addressed this, can be closed.
